{"name": "Проверка корректной ошибки при попытки авторизации с некорректным паролем", "status": "passed", "attachments": [{"name": "stdout", "source": "1b4a4d0e-1ea7-4748-a7f1-3d9cb41e319c-attachment.txt", "type": "text/plain"}], "start": 1733686233367, "stop": 1733686233643, "uuid": "0137a68d-81c1-4cbd-b861-198ef4a5533f", "historyId": "9699b600ff3621aeb7cf0246a5fd1dd0", "testCaseId": "9699b600ff3621aeb7cf0246a5fd1dd0", "fullName": "tests.test_login user.TestLoginUser#test_login_with_incorrect_password", "labels": [{"name": "feature", "value": "Логин пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "Karinas-MacBook-Pro.local"}, {"name": "thread", "value": "18924-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login user"}]}