{"name": "Проверка корректной ошибки при некорректной авторизации: {test_data_key}", "status": "passed", "parameters": [{"name": "test_data", "value": "{'email': '', 'password': '1111'}"}], "start": 1733867477146, "stop": 1733867477451, "uuid": "5ad5bc1d-2043-4fb1-b5c2-118d8b9ca579", "historyId": "a8e136c398b60196aaf64638e461d22c", "testCaseId": "311718a49f0f75c6e906c1fb2ac9a549", "fullName": "tests.test_login user.TestLoginUser#test_login_error_handling", "labels": [{"name": "feature", "value": "Логин пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "Karinas-MacBook-Pro.local"}, {"name": "thread", "value": "8223-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login user"}]}